global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Microservices
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Infrastructure
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']
    metrics_path: '/metrics'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom application metrics
  - job_name: 'socket-io-metrics'
    static_configs:
      - targets: ['chat-service:3002']
    metrics_path: '/socket-metrics'
    scrape_interval: 10s

  - job_name: 'webrtc-metrics'
    static_configs:
      - targets: ['video-service:3003']
    metrics_path: '/webrtc-metrics'
    scrape_interval: 10s 